; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;Script per 
[platformio]
default_envs = esp32dev
extra_configs = upload_port.ini  ;questo per avere la porta di upload in un file separato non tracciato da git

[env]
extra_scripts = git_script.py

[esp32]
platform = espressif32@6.12.0
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
test_framework = unity
lib_deps = ; qua ci va messo tutto quello che è necessario per tutti gli ESP32

[debug]
debug_tool = esp-prog
debug_init_break = tbreak setup
debug_build_flags = -O0 -ggdb3 -g3
upload_speed = 921600
upload_protocol = esp-prog

[env:esp32dev]
extends = esp32
board = esp32dev
lib_deps =  ${esp32.lib_deps}

[env:esp32dev_debug]
extends =   debug
            env:esp32dev
        
